# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cb9a1397b08336133b7b7403866420b1c83cdf7553edd8022416cc4ccb2ea011e66c4a96faca356e098b9ef93e9f5407f885ea2a68b89aecbbcce6c2e0ae8b8
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>

test:
  secret_key_base: 68fa487afba744bc41b50adbc9fd87481c73520ca9fb4f9121c64fac72e33bde0af76e31bcbbbe16e67b1cdbb84ba967e78b0c4d6e12ff7cc7bbb595f1e482d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  
